name = "Fabric server optimizations"
author = "Hubble"
version = "1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c968582eb64799251e87ea61c0cb86250c1c224b7cd81b7241908737705a57f"

[versions]
fabric = "0.14.23"
minecraft = "1.19.4"
